/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROG_H_RPCGEN
#define _PROG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operands {
	char *line;
	char c;
};
typedef struct operands operands;

#define PROG1 444444
#define VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define SEARCH 1
extern  int * search_1(operands *, CLIENT *);
extern  int * search_1_svc(operands *, struct svc_req *);
extern int prog1_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SEARCH 1
extern  int * search_1();
extern  int * search_1_svc();
extern int prog1_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operands (XDR *, operands*);

#else /* K&R C */
extern bool_t xdr_operands ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROG_H_RPCGEN */
