/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "prog.h"

bool_t
xdr_operands (XDR *xdrs, operands *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->line, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->c))
		 return FALSE;
	return TRUE;
}
